version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-memory
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  book-agent:
    build: .
    container_name: book-agente
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
      - GROQ_API_KEY_FILE=/run/secrets/groq_api_key
    volumes:
      - ./doc/book-agent-api-3156cc932afc.json:/app/credentials/credentials.json:ro
    depends_on:
      - redis
    networks:
      - app-network
    secrets:
      - groq_api_key
    env_file:
    - .env  

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge

secrets:
  groq_api_key:
    file: ./secrets/groq_api_key.txt

